export const mockData = {
  users: [
    { id: 1, username: 'Nguyễn Văn A', avatar: 'https://i.pravatar.cc/150?u=1' },
    { id: 2, username: 'Trần Thị B', avatar: 'https://i.pravatar.cc/150?u=2' },
  ],
  topUpvoteRevision: {
    id: 1,
    author: { id: 1, username: 'Nguyễn Văn A', avatar: 'https://i.pravatar.cc/150?u=1' },
    upvote_count: '18k',
    status: 'ĐÃ KIỂM DUYỆT',
    diff: [
      { type: 'unchanged', text: '[-...triều đại...] [+...triều Lý...]' },
      { type: 'added', text: '+[-...triều đại...] [+...triều Lý...]' },
      { type: 'removed', text: '-[-...triều đại...] -Lịch sử Gốm sứ nhà...' },
      { type: 'added', text: '+[...triều đại...] +current chămsứ nhà...]' },
      { type: 'empty', text: '' },
      { type: 'unchanged', text: '[-...triều đại...] [+..Việt Gốm Sứ...]' }
    ]
  },
  topLikeArticle: {
    id: 1,
    title: 'Lịch sử Gốm sứ nhà Minh',
    summary: 'Lịch sử Gốm sứ nhà Minh là chiến sư Vận, là chúng khôn gã Sứ Việt văn Bì vĩ nhất mặt vâng công sứ tiếng ở vùng khiển của chính sứa...',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Ming_Dynasty_Vase.jpg/800px-Ming_Dynasty_Vase.jpg',
    like_count: 5000,
    dislike_count: 500,
  },
  countries: [
    { id: 1, name: 'Việt Nam', code: 'VN', flag: '🇻🇳' },
    { id: 2, name: 'Trung Quốc', code: 'CN', flag: '🇨🇳' },
    { id: 3, name: 'Pháp', code: 'FR', flag: '🇫🇷' },
    { id: 4, name: 'Nhật Bản', code: 'JP', flag: '🇯🇵' },
    { id: 5, name: 'China', code: 'CN', flag: '🇨🇳' }, // Based on mockup duplication
    { id: 6, name: 'Bussia', code: 'RU', flag: '🇷🇺' }, // Based on mockup typo "Bussia" -> Russia flag
    { id: 7, name: 'Trung Quốc', code: 'CN', flag: '🇨🇳' }, // Based on mockup duplication
    { id: 8, name: 'Vàng Bno', code: 'IT', flag: '🇮🇹' }, // Placeholder flag
    { id: 9, name: 'Vietnam', code: 'VN', flag: '🇧🇬' }, // Based on mockup flag (looks like Bulgaria for "Vietnam")
    { id: 10, name: 'Rai rian', code: 'RO', flag: '🇷🇴' }, // Placeholder flag
    { id: 11, name: 'Neutria', code: 'NL', flag: '🇳🇱' }, // Placeholder flag
    { id: 12, name: 'Cammark', code: 'ZA', flag: '🇿🇦' }, // Placeholder flag
  ],
  categories: [
    { id: 1, name: 'Lịch sử Thể thao', icon: '⚽' },
    { id: 2, name: 'Cổ vật và Di tích', icon: '🏛️' },
    { id: 3, name: 'Tác giả nổi tiếng', icon: '👤' },
    { id: 4, name: 'Cổ vật và Di tích', icon: '🏺' },
    { id: 5, name: 'Tác giả nổi tiếng', icon: '📝' },
    { id: 6, name: 'Tác giả thao', icon: '⚙️' },
    { id: 7, name: 'Tác giả thử', icon: '🔬' },
    { id: 8, name: 'Tác giả nổi tiếng', icon: '🌍' },
    { id: 9, name: 'Tác giả thao', icon: '⚖️' },
    { id: 10, name: 'Tác giả nổi tiếng', icon: '👨‍🏫' },
    { id: 11, name: 'Tác giả Article', icon: '📑' },
  ],
  recentRevisions: [
    { id: 1, author: 'Nguyễn Văn A', action: 'edited', title: 'fue text revisions', timeAgo: '1 minutes ago' },
    { id: 2, author: 'Nguyễn Văn A', action: 'edited', title: 'the origimes content', timeAgo: '4 hours ago' },
    { id: 3, author: 'Nguyễn Văn A', action: 'edited', title: 'hiirsenturatos', timeAgo: '7 hrs ago' },
  ],
  recentArticles: [
    {
      id: 2,
      title: 'Lịch sử Gốm sứ nhà Minh',
      summary: 'Lịch sử Gốm sứ nhà Minh - Vác consemtry sứ Virsám của Việt chang ban trừ và lờt khứ nàn vào bán và lóin thông sứ tiết tìm hoặc gân liệm...',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Ming_Dynasty_Vase.jpg/800px-Ming_Dynasty_Vase.jpg',
    },
    {
      id: 3,
      title: 'Lịch sử Gốm sứ nhà Minh',
      summary: 'Lịch sử Gốm sứ nhà Minh - Vác consemtry sứ Virsám hãm chú cùng nhà tạo nuốn tố tiết ánh nhân thô cuốn đứng trán chùng của...',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/A_River_Landscape_with_Fishermen_%28Jan_van_Goyen%29.jpg/800px-A_River_Landscape_with_Fishermen_%28Jan_van_Goyen%29.jpg',
    }
  ]
};

export const searchArticles = [
  {
    id: 1,
    title: 'Amazonian Civilization and History',
    description: 'Explore the rich history of pre-Columbian Amazonian civilizations, their culture, agriculture, and trade networks.',
    category: 'Civilizations',
    country: 'Brazil',
    likes: 2340,
    comments: 156,
    views: 12500,
    image: 'https://thumbs.dreamstime.com/b/ancient-amazon-civilization-buildings-groups-people-scene-features-impressive-stone-wood-structures-intricate-329570180.jpg',
  },
  {
    id: 2,
    title: 'Ancient Egyptian Architecture',
    description: 'The monumental architecture of ancient Egypt, from pyramids to temples, showcasing engineering marvels of the ancient world.',
    category: 'Architecture',
    country: 'Egypt',
    likes: 5678,
    comments: 423,
    views: 28900,
    image: 'https://www.egypttoursportal.com/images/2024/04/Kom-Ombo-Tempel-Design-Ancient-Egyptian-Architecture-Egypt-Tours-Portal.jpg',
  },
  {
    id: 3,
    title: 'Ancient Greece: Democracy and Philosophy',
    description: 'Study the foundations of democracy in ancient Greece and the philosophical contributions of Socrates, Plato, and Aristotle.',
    category: 'Philosophy',
    country: 'Greece',
    likes: 3420,
    comments: 287,
    views: 18700,
    image: 'https://tse3.mm.bing.net/th/id/OIP.2u5BsB4I-VkkLgORSufJOQHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 4,
    title: 'Aztec Empire and Culture',
    description: 'Comprehensive overview of the Aztec Empire, their capital Tenochtitlan, religious practices, and conquest by Spanish conquistadors.',
    category: 'Empires',
    country: 'Mexico',
    likes: 2890,
    comments: 201,
    views: 15600,
    image: 'https://tse2.mm.bing.net/th/id/OIP.PdB9yjPSunPOlmpjwYD4qAHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
  },
  {
    id: 5,
    title: 'Byzantine Empire: Eastern Roman Legacy',
    description: 'The continuation of Roman civilization through the Byzantine Empire, spanning over 1000 years of history.',
    category: 'Empires',
    country: 'Turkey',
    likes: 1950,
    comments: 142,
    views: 9800,
    image: 'https://th.bing.com/th/id/R.79608d79d096eeb61b5ec5729b3b0af3?rik=sDGBBUAcQguB3w&riu=http%3a%2f%2fbrewminate.com%2fwp-content%2fuploads%2f2017%2f01%2fByzantineEmpire02.jpg&ehk=nPFAujnnfgM4T%2fs9DZONubfMppo2TENF6YXQR4EIxeE%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    id: 6,
    title: 'Chinese Dynasties and Imperial Rule',
    description: 'Trace the evolution of Chinese civilization through its many dynasties, from the Yellow River civilization to the Qing Dynasty.',
    category: 'Dynasties',
    country: 'China',
    likes: 4567,
    comments: 356,
    views: 22400,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Forbidden_City_with_Snow.jpg/800px-Forbidden_City_with_Snow.jpg',
  },
  {
    id: 7,
    title: 'Crusades: Religion and Warfare in Medieval Times',
    description: 'An analysis of the Crusades, holy wars fought between Christian and Muslim forces during the Medieval period.',
    category: 'Wars',
    country: 'Israel',
    likes: 2134,
    comments: 178,
    views: 11200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Carte_des_diverses_croisades.jpg/800px-Carte_des_diverses_croisades.jpg',
  },
  {
    id: 8,
    title: 'Dark Ages: Transition from Rome to Medieval Europe',
    description: 'Understanding the transition period after the fall of the Roman Empire and the emergence of Medieval Europe.',
    category: 'Medieval',
    country: 'Europe',
    likes: 1678,
    comments: 124,
    views: 8450,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Lindisfarne_Gospel_cross-carpet_page.jpg/800px-Lindisfarne_Gospel_cross-carpet_page.jpg',
  },
  {
    id: 9,
    title: 'Eastern Han Dynasty: Golden Age of China',
    description: 'The Eastern Han period marked a revival and flourishing of Chinese culture, technology, and science.',
    category: 'Dynasties',
    country: 'China',
    likes: 1456,
    comments: 98,
    views: 7200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Terracotta_Army.jpg/800px-Terracotta_Army.jpg',
  },
  {
    id: 10,
    title: 'French Revolution: From Monarchy to Republic',
    description: 'Explore the transformative French Revolution that reshaped European politics and society.',
    category: 'Revolutions',
    country: 'France',
    likes: 3890,
    comments: 267,
    views: 19500,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Liberty_leading_the_people.jpg/800px-Liberty_leading_the_people.jpg',
  },
  {
    id: 11,
    title: 'Gutenberg and the Printing Revolution',
    description: 'The invention of the printing press revolutionized the spread of knowledge and transformed European civilization.',
    category: 'Technology',
    country: 'Germany',
    likes: 2234,
    comments: 156,
    views: 10800,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/GutenbergBible.jpg/800px-GutenbergBible.jpg',
  },
  {
    id: 12,
    title: 'Hindu Civilization: Ancient India',
    description: 'Comprehensive history of ancient Hindu civilization, Vedic literature, and the development of Indian philosophy.',
    category: 'Civilizations',
    country: 'India',
    likes: 2567,
    comments: 189,
    views: 12300,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Taj_Mahal_in_Agra.jpg/800px-Taj_Mahal_in_Agra.jpg',
  },
  {
    id: 13,
    title: 'Inca Empire: Master Builders of the Andes',
    description: 'The Inca civilization and their remarkable achievements in architecture, administration, and engineering.',
    category: 'Empires',
    country: 'Peru',
    likes: 3123,
    comments: 215,
    views: 15800,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Machu_Picchu%2C_Peru.jpg/800px-Machu_Picchu%2C_Peru.jpg',
  },
  {
    id: 14,
    title: 'Islamic Golden Age: Science and Culture',
    description: 'The Islamic Golden Age produced remarkable advances in mathematics, astronomy, medicine, and philosophy.',
    category: 'Culture',
    country: 'Iraq',
    likes: 2876,
    comments: 198,
    views: 14200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Baghdad_Observatory.jpg/800px-Baghdad_Observatory.jpg',
  },
  {
    id: 15,
    title: 'Japanese Samurai and Feudal Society',
    description: 'The history of the samurai warrior class and the feudal structure of medieval and early modern Japan.',
    category: 'Culture',
    country: 'Japan',
    likes: 4012,
    comments: 289,
    views: 20100,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Samurai_in_armor.jpg/800px-Samurai_in_armor.jpg',
  },
  {
    id: 16,
    title: 'Korean Kingdoms and Three Kingdoms Era',
    description: 'The history of Korea through its various kingdoms including Goguryeo, Baekje, Silla, and later periods.',
    category: 'Kingdoms',
    country: 'South Korea',
    likes: 1789,
    comments: 134,
    views: 8900,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Bulguksa_Temple%2C_Korea.jpg/800px-Bulguksa_Temple%2C_Korea.jpg',
  },
  {
    id: 17,
    title: 'Leonardo da Vinci: Renaissance Master',
    description: 'The life and works of Leonardo da Vinci, the quintessential Renaissance artist and scientist.',
    category: 'Art',
    country: 'Italy',
    likes: 5432,
    comments: 398,
    views: 26700,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
  },
  {
    id: 18,
    title: 'Magna Carta: Foundation of Democracy',
    description: 'The Magna Carta of 1215 established fundamental principles of law and governance that influenced democracy.',
    category: 'Law',
    country: 'England',
    likes: 1923,
    comments: 145,
    views: 9600,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Magna_Carta%2C_British_Library_Cotton_MS_Augustus_II.106.jpg/800px-Magna_Carta%2C_British_Library_Cotton_MS_Augustus_II.106.jpg',
  },
  {
    id: 19,
    title: 'Mesopotamian Civilization: Cradle of History',
    description: 'The ancient civilizations of Mesopotamia, including Sumeria, Akkad, Babylon, and the origins of writing.',
    category: 'Civilizations',
    country: 'Iraq',
    likes: 2654,
    comments: 201,
    views: 13200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Ur_of_the_Chaldees.jpg/800px-Ur_of_the_Chaldees.jpg',
  },
  {
    id: 20,
    title: 'Ming Dynasty: China\'s Golden Age',
    description: 'The Ming Dynasty period marked one of China\'s most prosperous and culturally rich eras.',
    category: 'Dynasties',
    country: 'China',
    likes: 3756,
    comments: 267,
    views: 18900,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Ming_Dynasty_Vase.jpg/800px-Ming_Dynasty_Vase.jpg',
  },
  {
    id: 21,
    title: 'Norman Conquest and Medieval England',
    description: 'The Norman Conquest of 1066 and its profound impact on English history and culture.',
    category: 'Medieval',
    country: 'England',
    likes: 1534,
    comments: 112,
    views: 7700,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Bayeux_Tapestry_-_Battle_of_Hastings.jpg/800px-Bayeux_Tapestry_-_Battle_of_Hastings.jpg',
  },
  {
    id: 22,
    title: 'Ottoman Empire: Bridge Between Continents',
    description: 'The Ottoman Empire\'s history, culture, and influence spanning from Asia to Europe and Africa.',
    category: 'Empires',
    country: 'Turkey',
    likes: 2987,
    comments: 209,
    views: 14800,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Istanbul_Topkapi_Palace.jpg/800px-Istanbul_Topkapi_Palace.jpg',
  },
  {
    id: 23,
    title: 'Philosophers of Ancient Greece',
    description: 'Detailed examination of Socrates, Plato, and Aristotle and their revolutionary philosophical ideas.',
    category: 'Philosophy',
    country: 'Greece',
    likes: 2165,
    comments: 167,
    views: 10900,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Socrates_Louvre.jpg/800px-Socrates_Louvre.jpg',
  },
  {
    id: 24,
    title: 'Qin Dynasty: First Imperial Dynasty of China',
    description: 'The Qin Dynasty unified China and established the foundations of the imperial system.',
    category: 'Dynasties',
    country: 'China',
    likes: 2043,
    comments: 156,
    views: 10200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Qin_Terracotta_Warriors.jpg/800px-Qin_Terracotta_Warriors.jpg',
  },
  {
    id: 25,
    title: 'Russian Empire and Tsardom',
    description: 'The history of Russia from the Grand Duchy of Moscow through the Romanov dynasty.',
    category: 'Empires',
    country: 'Russia',
    likes: 2298,
    comments: 178,
    views: 11500,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Winter_Palace%2C_Saint_Petersburg.jpg/800px-Winter_Palace%2C_Saint_Petersburg.jpg',
  },
  {
    id: 26,
    title: 'Spanish Inquisition and Religious History',
    description: 'The Spanish Inquisition and its complex role in Spanish history and religious life.',
    category: 'Religion',
    country: 'Spain',
    likes: 1876,
    comments: 134,
    views: 9400,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Goya_Inquisition.jpg/800px-Goya_Inquisition.jpg',
  },
  {
    id: 27,
    title: 'Tang Dynasty: China\'s Cosmopolitan Age',
    description: 'The Tang Dynasty was a golden age of Chinese history marked by cultural flourishing and territorial expansion.',
    category: 'Dynasties',
    country: 'China',
    likes: 2345,
    comments: 189,
    views: 11800,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Tang_Dynasty_Vase.jpg/800px-Tang_Dynasty_Vase.jpg',
  },
  {
    id: 28,
    title: 'University System in Medieval Europe',
    description: 'The origins and development of universities in Medieval Europe and their role in preserving knowledge.',
    category: 'Education',
    country: 'Italy',
    likes: 1234,
    comments: 98,
    views: 6200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/University_of_Paris.jpg/800px-University_of_Paris.jpg',
  },
  {
    id: 29,
    title: 'Vietnamese History: From Ancient Times',
    description: 'The fascinating history of Vietnam from its ancient origins through various dynasties and colonial periods.',
    category: 'Civilizations',
    country: 'Vietnam',
    likes: 3456,
    comments: 234,
    views: 17200,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Ha_Noi_Temple_of_Literature.jpg/800px-Ha_Noi_Temple_of_Literature.jpg',
  },
  {
    id: 30,
    title: 'Western Roman Empire: Rise and Fall',
    description: 'The history of the Western Roman Empire from its height to its fall in 476 CE.',
    category: 'Empires',
    country: 'Italy',
    likes: 3678,
    comments: 289,
    views: 18300,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Rome_Colosseum.jpg/800px-Rome_Colosseum.jpg',
  },
];
